name: Mail-VersionTracker
version: 1.10
abstract: Parses newsletters from versiontracker.com
author: Adam J. Foxson <afoxson@pobox.com>
license: gpl
distribution_type: module
requires:
  Mail::Internet: 1.60
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.27
